### ISSUE TITLE
...luarocks/rocks-5.3/tarantoolapp/1.0.3-1/bin/tarantoolapp:9: module 'tarantoolapp.argparse' not found

### ISSUE THREAD

**Issue by shapel** [moonlibs/tarantoolapp#11]
tarantoolapp create myapp
Tarantool version: 1.10.2-1-ge0017ad
...luarocks/rocks-5.3/tarantoolapp/1.0.3-1/bin/tarantoolapp:9: module 'tarantoolapp.argparse' not found:
	no field package.preload['tarantoolapp.argparse']
	no file './tarantoolapp/argparse.lua'
	no file './tarantoolapp/argparse/init.lua'
	no file './tarantoolapp/argparse.dylib'
	no file './tarantoolapp/argparse.so'
	no file '/Users/pavel/dev/lua/.rocks/share/tarantool/tarantoolapp/argparse.lua'
	no file '/Users/pavel/dev/lua/.rocks/share/tarantool/tarantoolapp/argparse/init.lua'
	no file '/Users/pavel/dev

**Comment by igorcoding** [comment]
You should install lua 5.1. Other lua versions are not supported by Tarantool.

**Comment by shapel** [comment]
You are right!

**Comment by ArturAralin** [comment]
@igorcoding I'll got the same problem. I'd tried to install lua 5.1 and set lua interpreter version to luarocks config, but he's ignoring my changes

`tarantoolapp create app`
```
Tarantool version: 1.10.2-1-ge0017ad
...luarocks/rocks-5.3/tarantoolapp/1.0.3-1/bin/tarantoolapp:9: module 'tarantoolapp.argparse' not found:
	no field package.preload['tarantoolapp.argparse']
	no file './tarantoolapp/argparse.lua'
	no file './tarantoolapp/argparse/init.lua'
	no file './tarantoolapp/argparse.dylib'
	no file './tarantoolapp/argparse.so'
	no file '/usr/local/Cellar/lua/5.3.5_1/.rocks/share/tarantool/tarantoolapp/argparse.lua'
	no file '/usr/local/Cellar/lua/5.3.5_1/.rocks/share/tarantool/tarantoolapp/argparse/init.lua'
	no file
```

```
-- LuaRocks configuration

rocks_trees = {
   { name = "user", root = home .. "/.luarocks" };
   { name = "system", root = "/usr/local" };
}
lua_interpreter = "lua-5.1";
variables = {
   LUA = "/usr/local/bin/lua-5.1";
   LUA_DIR = "/usr/local/bin";
   LUA_BINDIR = "/usr/local/opt/lua/bin";
}
```

**Comment by igorcoding** [comment]
Have you tried reinstalling tarantoolapp after changing lua paths?
It's clear that it uses lua 5.3 paths. Try making sure that you have luarocks for 5.1

**Comment by ArturAralin** [comment]
I'd made next

```
brew install lua@5.1
// now command lua starts lua5.1
brew install luarocks
brew install tarantool
```
problem had not solved

**Comment by ArturAralin** [comment]
I'd look to brew formulae (https://formulae.brew.sh/api/formula/luarocks.json)
inside the dependencies: 
```
dependencies: [
   "lua@5.1",
  "lua"
],
```

**Comment by igorcoding** [comment]
But still - have you reinstalled this module (tarantoolapp)?

**Comment by ArturAralin** [comment]
Yep. I'd reinstall him.

I'd created `~./luarocks/config-5.1.lua` and put into

```
variables = {
  LUA_DIR = "/usr/local/opt/lua";
  LUA_BINDIR = "/usr/local/bin";
}
```

and `tarantoolapp create test` output me

```
Tarantool version: 1.10.2-1-ge0017ad
error loading module 'tarantoolapp.argparse' from file '/usr/local/bin/lua-5.1':
	/usr/local/bin/lua-5.1:1: '=' expected near 'char(7)'
```

**Comment by igorcoding** [comment]
This is really weird. I don't have Mac os near right now to check into this. But I'll try to look today.
@shapel maybe you can help somehow with this?

**Comment by ArturAralin** [comment]
@igorcoding this sad((
My PM will be crying and possibly will be scream abusive words.

p.s. SOS 👀

**Comment by igorcoding** [comment]
I'm not an expert in macos and brew stuff but tried this on a fresh system:
```
brew install lua@5.1
brew install luarocks
brew install tarantool
luarocks --lua-dir=/usr/local/opt/lua@5.1 install tarantoolapp
```

After this tarantoolapp has been installed to the home dir and `create` command run successfully.

**Comment by ArturAralin** [comment]
The same problem. Tarantool tries to load module from bin file `/usr/local/bin/lua-5.1` instead.

```
Tarantool version: 1.10.2-1-ge0017ad
error loading module 'tarantoolapp.argparse' from file '/usr/local/bin/lua-5.1':
	/usr/local/bin/lua-5.1:1: '=' expected near 'char(7)'
```

Before this I'd removed all packages and install all again

**Comment by v-kryuchkov** [comment]
`luarocks --lua-dir=/usr/local/opt/lua@5.1 install tarantoolapp`

Is solved for me

**Comment by ArturAralin** [comment]
Possibility I must clear all created folders and try again

**Comment by ArturAralin** [comment]
God blessing! I have solved my problem. `luarocks` just want to get a lua version directly into config `lua_version = "5.1"`

```
-- LuaRocks configuration

rocks_trees = {
   { name = "user", root = home .. "/.luarocks" };
   { name = "system", root = "/usr/local" };
}
lua_version = "5.1" -- <--- JUST A ONE PARAMETER WHICH MAKE ME FEEL PAIN
lua_interpreter = "lua5.1";
variables = {
   LUA_DIR = "/usr/local/opt/lua@5.1";
   LUA_BINDIR = "/usr/local/opt/lua@5.1/bin";
   LUA_INCDIR = "/usr/local/opt/lua@5.1/include";
   LUA_LIBDIR = "/usr/local/opt/lua@5.1/lib";
}
```

**Comment by igorcoding** [comment]
Glad it solved :)
I think, I'll add this config to readme
